Repository dlang/dub, pull requests merged in 2018-12, with the labels that each got.

#1602 when running `dub build :<subpackage>`, explicitly load subpackage in current folder.
  source/dub/commandline.d
Labels: 72h no objection -> merge

#1589 Add experimental feature to improve build cache efficiency
  changelog/version-identifier-filter.dd
  source/dub/commandline.d
  source/dub/compilers/buildsettings.d
  source/dub/dub.d
  source/dub/generators/generator.d
  source/dub/package_.d
  source/dub/project.d
  source/dub/recipe/json.d
  source/dub/recipe/packagerecipe.d
  source/dub/recipe/sdl.d
  test/4-describe-data-1-list.sh
  test/4-describe-data-2-dmd.sh
  test/describe-dependency-1/source/dummy.d
  test/describe-project/src/dummy.d
  test/version-filters-diamond/.gitignore
  test/version-filters-diamond/.no_build
  test/version-filters-diamond/.no_run
  test/version-filters-diamond/.no_test
  test/version-filters-diamond/daughter/.gitignore
  test/version-filters-diamond/daughter/dub.sdl
  test/version-filters-diamond/daughter/source/dummy.d
  test/version-filters-diamond/diamond/.gitignore
  test/version-filters-diamond/diamond/dub.sdl
  test/version-filters-diamond/diamond/source/dummy.d
  test/version-filters-diamond/dub.sdl
  test/version-filters-diamond/son/.gitignore
  test/version-filters-diamond/son/dub.sdl
  test/version-filters-diamond/son/source/dummy.d
  test/version-filters-diamond/source/app.d
  test/version-filters-none/.gitignore
  test/version-filters-none/.no_build
  test/version-filters-none/.no_run
  test/version-filters-none/.no_test
  test/version-filters-none/dub.sdl
  test/version-filters-none/source/app.d
  test/version-filters-source-dep/.gitignore
  test/version-filters-source-dep/.no_build
  test/version-filters-source-dep/.no_run
  test/version-filters-source-dep/.no_test
  test/version-filters-source-dep/dub.sdl
  test/version-filters-source-dep/source-dep/dub.sdl
  test/version-filters-source-dep/source-dep/source/dummy.d
  test/version-filters-source-dep/source/app.d
  test/version-filters.sh
  test/version-filters/.gitignore
  test/version-filters/.no_build
  test/version-filters/.no_run
  test/version-filters/.no_test
  test/version-filters/daughter/.gitignore
  test/version-filters/daughter/dub.sdl
  test/version-filters/daughter/source/dummy.d
  test/version-filters/dub.sdl
  test/version-filters/son/.gitignore
  test/version-filters/son/dub.sdl
  test/version-filters/son/source/dummy.d
  test/version-filters/source/app.d
Labels: auto-merge

#1622 Merge remote-tracking branch 'upstream/stable' into merge_stable
  source/dub/version_.d
Labels: auto-merge

#1571 toolchainRequirements recipe support
  changelog/toolchain_requirements.dd
  source/dub/compilers/compiler.d
  source/dub/compilers/dmd.d
  source/dub/compilers/gdc.d
  source/dub/compilers/ldc.d
  source/dub/compilers/utils.d
  source/dub/generators/build.d
  source/dub/package_.d
  source/dub/platform.d
  source/dub/recipe/json.d
  source/dub/recipe/packagerecipe.d
  source/dub/recipe/sdl.d
  test/issue1531-toolchain-requirements.sh
Labels: auto-merge

#1592 improve package supplier fallback logic
  source/dub/commandline.d
  source/dub/dub.d
  source/dub/packagesuppliers/fallback.d
  test/feat663-search.sh
Labels: Bug Fix, auto-merge, needs review, trivial

#1626 fixup #1587 - cleanup and version-spec support for dub add
  changelog/addcommand.dd
  source/dub/commandline.d
  test/issue1574-addcommand.sh
Labels: auto-merge

#1627 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/addcommand.dd
  source/dub/commandline.d
  source/dub/dub.d
  source/dub/packagesuppliers/fallback.d
  source/dub/version_.d
  test/4-describe-data-2-dmd.sh
  test/feat663-search.sh
  test/issue1574-addcommand.sh
Labels: Bug Fix
