Repository dlang/dub, pull requests merged in 2018-03, with the labels that each got.

#1404 Merge remote-tracking branch 'upstream/stable' into merge_stable
  source/dub/version_.d
Labels: auto-merge

#1409 Inherit linker sourceFiles as sourceFiles instead of linkerFiles
  CHANGELOG.md
  appveyor.yml
  source/dub/generators/generator.d
  test/issue1408-inherit-linker-files/.no_run
  test/issue1408-inherit-linker-files/.no_test
  test/issue1408-inherit-linker-files/dep.d
  test/issue1408-inherit-linker-files/dub.sdl
  test/issue1408-inherit-linker-files/lib.d
  test/issue1408-inherit-linker-files/lib/dub.sdl
  test/issue1408-inherit-linker-files/lib/lib.d
  test/issue1408-inherit-linker-files/main.d
Labels: needs review

#1413 Fix #1412 - wait longer until Vibe.d has started
  test/fetchzip.sh
Labels: trivial
