Repository dlang/dub, pull requests merged in 2018-11, with the labels that each got.

#1586 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/betterC_build_option.dd
  changelog/env_var_package_version.dd
  source/dub/version_.d
Labels: auto-merge

#1588 Use default architecture for ddox
  source/dub/dub.d
Labels: auto-merge

#1591 Retry download for registry search packages
  source/dub/packagesuppliers/registry.d
Labels: auto-merge

#1526 Late dependencies resolver
  source/dub/dub.d
  source/dub/project.d
  test/issue1524-maven-upgrade-dependency-tree.sh
  test/issue1524-maven-upgrade-dependency-tree.sh.min_frontend
  test/issue1524-maven-upgrade-dependency-tree/.gitignore
  test/issue1524-maven-upgrade-dependency-tree/.no_build
  test/issue1524-maven-upgrade-dependency-tree/dub.json
  test/issue1524-maven-upgrade-dependency-tree/maven/release/dubpackages/maven-dubpackage-a/1.0.5/maven-dubpackage-a-1.0.5.zip
  test/issue1524-maven-upgrade-dependency-tree/maven/release/dubpackages/maven-dubpackage-a/maven-metadata.xml
  test/issue1524-maven-upgrade-dependency-tree/maven/release/dubpackages/maven-dubpackage-b/1.0.6/maven-dubpackage-b-1.0.6.zip
  test/issue1524-maven-upgrade-dependency-tree/maven/release/dubpackages/maven-dubpackage-b/maven-metadata.xml
  test/issue1524-maven-upgrade-dependency-tree/source/app.d
Labels: 72h no objection -> merge, auto-merge

#1590 Fix temp copy files
  source/dub/generators/build.d
  source/dub/generators/generator.d
  test/issue1136-temp-copy-files.sh
  test/issue1136-temp-copy-files/.no_build
  test/issue1136-temp-copy-files/app.d
  test/issue1136-temp-copy-files/mylib/dub.sdl
  test/issue1136-temp-copy-files/mylib/helloworld.txt
Labels: auto-merge

#1582 Pre/post run commands added
  changelog/pre-post-run-commands.dd
  source/dub/compilers/buildsettings.d
  source/dub/description.d
  source/dub/generators/build.d
  source/dub/generators/generator.d
  source/dub/project.d
  source/dub/recipe/json.d
  source/dub/recipe/packagerecipe.d
  source/dub/recipe/sdl.d
  test/issue1396-pre-post-run-commands.sh
  test/issue1396-pre-post-run-commands/.no_build
  test/issue1396-pre-post-run-commands/dub.sdl
  test/issue1396-pre-post-run-commands/post-run.sh
  test/issue1396-pre-post-run-commands/source/app.d
Labels: auto-merge

#1597 Update addcommand.dd
  changelog/addcommand.dd
Labels: auto-merge

#1598 Fix travis ci
  test/issue1574-addcommand.sh
  test/issue1574-addcommand.sh.min_frontend
Labels: auto-merge

#1600 Fix wrong cast
  source/dub/generators/generator.d
Labels: auto-merge

#1601 Merge pull request #1600 from RazvanN7/fix_cast
  appveyor.yml
  source/dub/generators/generator.d
  test/interactive-remove.sh
  travis-ci.sh
Labels: auto-merge

#1549 Adding support for $DUB variable
  build-gdc.sh
  build.cmd
  build.sh
  changelog/dubEnvVar.dd
  dub.sdl
  source/dub/generators/generator.d
  source/dub/internal/utils.d
  source/dub/project.d
  test/pr1549-dub-exe-var.sh
  test/pr1549-dub-exe-var/.gitignore
  test/pr1549-dub-exe-var/.no_build
  test/pr1549-dub-exe-var/dub.sdl
  test/pr1549-dub-exe-var/setmsg.d
  test/pr1549-dub-exe-var/source/app.d
Labels: 72h no objection -> merge
