Repository dlang/dub, pull requests merged in 2018-10, with the labels that each got.

#1532 implement "minDubVersion" field
  changelog/minDubVersion.dd
  source/dub/package_.d
  source/dub/recipe/json.d
  source/dub/recipe/packagerecipe.d
  source/dub/recipe/sdl.d
  test/issue1531-min-dub-version.sh
Labels: 72h no objection -> merge

#1576 Merge remote-tracking branch 'upstream/stable' into merge_stable
  CHANGELOG.md
  source/dub/version_.d
Labels: auto-merge, stable -> master

#1579 GitHub's API + UI don't return 0.9.20 anymore
  test/interactive-remove.sh
  travis-ci.sh
Labels: auto-merge

#1569 Fix Issue #1504
  source/dub/recipe/packagerecipe.d
  test/issue1504-envvar-in-path.sh
  test/issue1504-envvar-in-path/.no_build
  test/issue1504-envvar-in-path/dub.json
  test/issue1504-envvar-in-path/source/app.d
  test/issue1504-envvar-in-path/teststrings/message.txt
Labels: Bug Fix, auto-merge
