Repository dlang/dub, pull requests merged in 2018-02, with the labels that each got.

#1376 [Trivial] Need to use '/usr/bin/env bash' instead of '/bin/bash'
  test/fetchzip.sh
Labels: auto-merge, trivial

#1377 Fix 1037 (rebased against master)
  source/dub/dependencyresolver.d
  test/expected-issue1037-output
  test/issue1037-better-dependency-messages.sh
  test/issue1037-better-dependency-messages/.no_build
  test/issue1037-better-dependency-messages/.no_run
  test/issue1037-better-dependency-messages/.no_test
  test/issue1037-better-dependency-messages/b/dub.json
  test/issue1037-better-dependency-messages/dub.json
Labels: auto-merge

#1384 Rename ConfigEntry to PackageConfigs and avoid GC allocation.
  source/dub/dependencyresolver.d
Labels: auto-merge

#1385 Remove on:master from the Travis stage conditions
  .travis.yml
Labels: auto-merge, trivial

#1387 Merge remote-tracking branch 'upstream/stable' into merge_stable
  CHANGELOG.md
  source/dub/version_.d
Labels: auto-merge

#1388 [auto-deploy] search for 32-bit DMD executable
  .travis.yml
Labels: trivial

#1394 Merge remote-tracking branch 'upstream/stable' into merge_stable
  source/dub/version_.d
Labels: auto-merge
