Repository dlang/dub, pull requests merged in 2019-03, with the labels that each got.

#1663 Merge remote-tracking branch 'upstream/stable' into merge_stable
  changelog/dub-fetch-shortcut.dd
  changelog/extraDependencyFiles-attribute-added.dd
  changelog/file-system-supplier.dd
  changelog/toolchain_requirements.dd
  source/dub/version_.d
Labels: auto-merge

#1658 Custom init type
  changelog/custom-dub-init-type.dd
  source/dub/commandline.d
  source/dub/dub.d
  source/dub/init.d
  test/issue1651-custom-dub-init-type.sh
  test/issue1651-custom-dub-init-type/.no_build
  test/issue1651-custom-dub-init-type/.no_run
  test/issue1651-custom-dub-init-type/.no_test
  test/issue1651-custom-dub-init-type/custom-dub-init-dubpackage-1.0.1.zip
Labels: 72h no objection -> merge

#1666 Upgrade dependencies
  dub.selections.json
  travis-ci.sh
Labels: auto-merge

#1662 Remove `dub list-installed` command
  changelog/remove-dub-list-installed.dd
  source/dub/commandline.d
Labels: auto-merge

#1668 Support of init-exec sub package
  changelog/custom-dub-init-type.dd
  source/dub/dub.d
  test/issue1651-custom-dub-init-type/custom-dub-init-dubpackage-1.0.1.zip
Labels: 72h no objection -> merge

#1674 Fix LDC versions for the deployment stage
  .travis.yml
Labels: auto-merge

#1661 Windows: Don't use Optlink by default
  changelog/dmd-mscoff-default.dd
  source/dub/compilers/dmd.d
Labels: auto-merge-squash
