Repository dlang/dub, pull requests merged in 2020-12, with the labels that each got.

#2047 Use DC env variable as the default compiler
  changelog/env-d-compiler.dd
  source/dub/dub.d
  test/dc-env.sh
  test/issue2012-dc-env/.no_build
  test/issue2012-dc-env/app.d
  test/issue895-local-configuration.sh
Labels: auto-merge

#2052 Fix #2051: Running unit tests from DUB single file packages fails
  .github/workflows/main.yml
  changelog/fix-2051.dd
  source/dub/dub.d
  test/.gitignore
  test/issue_2051_running_unittests_from_dub_single_file_packages_fails.d
Labels: Bug Fix, auto-merge

#2055 Improved ldc cross compile
  changelog/improved-ldc-cross-compile.dd
  source/dub/compilers/ldc.d
  source/dub/dub.d
  test/removed-dub-obj.sh
  test/removed-dub-obj/.no_build
  test/removed-dub-obj/.no_run
  test/removed-dub-obj/.no_test
  test/removed-dub-obj/dub.sdl
  test/removed-dub-obj/source/test.d
Labels: auto-merge

#2057 improve list command (filter by package spec)
  changelog/improved-list-command.dd
  source/dub/commandline.d
  test/version-spec.sh
Labels: auto-merge

#2048 Dont export DFLAGS & LFLAGS by default
  changelog/dont-propagate-flags.dd
  source/dub/generators/generator.d
  source/dub/project.d
Labels: auto-merge

#2040 Allow custom dflags to be defined for dependencies
  changelog/dependency-build-settings.dd
  source/dub/generators/generator.d
  source/dub/recipe/json.d
  source/dub/recipe/packagerecipe.d
  test/depen-build-settings/.gitignore
  test/depen-build-settings/.no_test
  test/depen-build-settings/depend/depend2/dub.json
  test/depen-build-settings/depend/depend2/source/depend2.d
  test/depen-build-settings/depend/dub.json
  test/depen-build-settings/depend/source/depend.d
  test/depen-build-settings/dub.json
  test/depen-build-settings/dub.selections.json
  test/depen-build-settings/source/app.d
Labels: auto-merge

#2058 Normalize line endings & UTF8 BOMs
  source/dub/internal/libInputVisitor.d
  source/dub/internal/sdlang/parser.d
  test/issue564-invalid-upgrade-dependency/a-1.0.0/source/a.d
  test/issue564-invalid-upgrade-dependency/a-1.1.0/source/a.d
  test/issue564-invalid-upgrade-dependency/main/source/app.d
Labels: trivial

#2056 add ability for specify version range for commandline commands
  changelog/add-ability-for-specify-version-range-for-commandline-commands.dd
  source/dub/commandline.d
  test/version-spec.sh
Labels: auto-merge

#2061 merge stable
  source/dub/compilers/ldc.d
  source/dub/generators/build.d
  source/dub/version_.d
Labels: auto-merge, stable -> master

#2063 Minor code cleanup (whitespace, import)
  source/dub/commandline.d
  source/dub/dub.d
Labels: Refactoring, auto-merge

#2062 Remove redundant code with relativeTo
  source/dub/generators/build.d
Labels: Refactoring, auto-merge

#2065 Set cwd on spawn functions instead of chdir
  source/dub/generators/build.d
Labels: auto-merge

#2064 Hotfix for #2051
  source/dub/commandline.d
  source/dub/dub.d
  source/dub/project.d
  test/issue_2051_running_unittests_from_dub_single_file_packages_fails.d
Labels: auto-merge

#2066 Renaming a file
  .github/workflows/main.yml
  test/issue2051_running_unittests_from_dub_single_file_packages_fails.d
Labels: auto-merge

#2067 Raise minimum Vibe.d requirement to v0.9.0
  dub.sdl
  source/dub/internal/vibecompat/inet/path.d
  source/dub/internal/vibecompat/inet/url.d
Labels: auto-merge

#2071 merge stable
  source/dub/version_.d
Labels: auto-merge

#2072 Cleanup http listener in vibed template
  source/dub/init.d
Labels: auto-merge
