Repository dlang/dub, pull requests merged in 2020-04, with the labels that each got.

#1920 Update test/*.min_frontend for several vibe.d tests to 2.077
  test/fetchzip.sh.min_frontend
  test/issue1180-local-cache-broken.sh.min_frontend
  test/issue1416-maven-repo-pkg-supplier.sh.min_frontend
  test/issue1524-maven-upgrade-dependency-tree.sh.min_frontend
  test/issue1574-addcommand.sh.min_frontend
Labels: auto-merge

#1921 merge stable
  changelog/env_variable_source_files_added.dd
  changelog/zsh-completion.dd
  source/dub/dub.d
  source/dub/version_.d
Labels: auto-merge, stable -> master

#1910 Use queryString to setup the pacakge parameters
  source/dub/packagesuppliers/registry.d
Labels: auto-merge

#1916 Fix issue 1372 -- hidden directories should be ignored unless explicitly included
  source/dub/recipe/packagerecipe.d
  test/issue1372-ignore-files-in-hidden-dirs.sh
  test/issue1372-ignore-files-in-hidden-dirs/.hiddensource/hello.d
  test/issue1372-ignore-files-in-hidden-dirs/dub.json
  test/issue1372-ignore-files-in-hidden-dirs/source/.AppleDouble/app.d
  test/issue1372-ignore-files-in-hidden-dirs/source/.compileMe/hello.d
  test/issue1372-ignore-files-in-hidden-dirs/source/app.d
Labels: auto-merge

#1925 Add changelog for #1372 fix
  changelog/ignoreHiddenDirectories.dd
Labels: auto-merge

#1927 merge stable
  source/dub/version_.d
Labels: auto-merge

#1929 Lint: Add --report-file argument
  changelog/lintReportFile.dd
  source/dub/commandline.d
  test/issue1773-lint.sh
Labels: auto-merge, enhancement
