Repository dlang/dub, pull requests merged in 2020-11, with the labels that each got.

#2032 Add support for '-platformlib' option. Fixes #2031
  source/dub/compilers/ldc.d
Labels: Bug Fix, auto-merge

#2036 GH Actions: Use new syntax for set-env
  .github/workflows/main.yml
Labels: CI, auto-merge

#2025 betterC flag enabled in generated visuald project file. Fixes #2024
  changelog/betterc-generated-in-visuald.dd
  source/dub/generators/visuald.d
Labels: enhancement

#2042 [CI]: Remove old AppVeyor, TravisCI, SemaphoreCI and build-gdc.sh files
  .travis.yml
  appveyor.yml
  build-gdc.sh
  semaphore-ci.sh
Labels: CI, trivial

#2049 [stable] Add support for --arch=x86_mscoff for LDC (for DMD compatibility)
  source/dub/compilers/ldc.d
Labels: auto-merge
