Repository dlang/dub, pull requests merged in 2020-01, with the labels that each got.

#1845 Fix issue 1277: Missing dub.json causes infinite loop
  source/dub/commandline.d
  test/issue1277.sh
  test/issue1277/.no_build
  test/issue1277/source/app.d
Labels: Bug Fix

#1848 Add a warning / workaround for issue 1474
  examples/generated-sources/dub.json
Labels: auto-merge

#1847 Add zsh completion script
  scripts/zsh-completion/_dub
Labels: enhancement

#1849 Use build.d everywhere, fix windows build
  CONTRIBUTING.md
  README.md
  build.d
  build.sh
  release-windows.sh
  release.sh
  scripts/rpm-package/dub.spec
  scripts/rpm-package/make_installer.sh
  setup-ldc-windows.sh
  travis-ci.sh
Labels: auto-merge

#1851 Merge remote-tracking branch 'upstream/stable' into merge_stable
  source/dub/version_.d
Labels: auto-merge

#1844 Clean up PackageManager handling of search path
  source/dub/dub.d
  source/dub/packagemanager.d
Labels: auto-merge

#1858 Add changelog entry for zsh-completion
  changelog/zsh-completion.dd
Labels: auto-merge
