Repository dlang/dub, pull requests merged in 2021-01, with the labels that each got.

#2074 merge stable
  changelog/add-ability-for-specify-version-range-for-commandline-commands.dd
  changelog/auto-exclude-main-from-other-configs.dd
  changelog/betterc-generated-in-visuald.dd
  changelog/cache-generated-test-config.dd
  changelog/dependency-build-settings.dd
  changelog/dont-propagate-flags.dd
  changelog/env-d-compiler.dd
  changelog/fix-2051.dd
  changelog/improved-ldc-cross-compile.dd
  changelog/improved-list-command.dd
  changelog/support-for-.netrc-file-added.dd
  source/dub/version_.d
Labels: auto-merge, stable -> master

#2082 Improve 'linker-D-flag' detection for ldmd2
  source/dub/compilers/dmd.d
  source/dub/compilers/ldc.d
Labels: auto-merge, dub-library-api

#2081 Allow adding dflags on dependencies when using SDL format
  source/dub/recipe/sdl.d
Labels: Bug Fix

#2083 Extend 'linker dflags' detection for DMD
  changelog/dmd-linker-dflags.dd
  source/dub/compilers/dmd.d
Labels: auto-merge, libdc

#2089 Selectively import symbols from std.array.
  source/dub/generators/generator.d
Labels: Refactoring, auto-merge

#2088 Remove unused selective imports.
  source/dub/compilers/compiler.d
  source/dub/compilers/dmd.d
  source/dub/compilers/gdc.d
  source/dub/compilers/ldc.d
  source/dub/dependencyresolver.d
Labels: Refactoring, auto-merge

#2090 Remove unused imports from compiler.d.
  source/dub/compilers/compiler.d
Labels: Refactoring, auto-merge

#2091 Refactor imports (inet.url -> inet.path).
  source/dub/package_.d
  source/dub/project.d
  source/dub/recipe/packagerecipe.d
Labels: Refactoring, auto-merge

#2092 Remove unused std.range import.
  source/dub/semver.d
Labels: Refactoring, auto-merge

#2093 Remove unused imports.
  source/dub/generators/sublimetext.d
Labels: Refactoring, auto-merge

#2094 Refactor imports.
  source/dub/dependency.d
Labels: Refactoring, auto-merge

#2097 Refactor import. Url is not used directly, but path is.
  source/dub/commandline.d
Labels: Refactoring, auto-merge

#2096 Remove unused imports.
  source/dub/compilers/dmd.d
  source/dub/compilers/gdc.d
  source/dub/compilers/ldc.d
Labels: Refactoring, auto-merge

#2095 Deprecate unused but public import.
  source/dub/compilers/compiler.d
Labels: auto-merge, dub-library-api

#2098 Fix #2085: [visuald] spurious library project
  source/dub/generators/visuald.d
  test/issue2085-target-none-visuald.sh
  test/issue2085-target-none-visuald/.no_build
  test/issue2085-target-none-visuald/.no_run
  test/issue2085-target-none-visuald/dub.json
  test/issue2085-target-none-visuald/sub/dub.json
  test/issue2085-target-none-visuald/sub/source/app.d
Labels: Bug Fix, auto-merge

#2102 Add some generated files to .gitignore
  .gitignore
Labels: auto-merge
