Repository dlang/dub, pull requests merged in 2021-03, with the labels that each got.

#1905 fix #1867 - Add lowmem for settings
  changelog/add_lowmem.dd
  source/dub/commandline.d
  source/dub/compilers/buildsettings.d
  source/dub/compilers/dmd.d
  source/dub/compilers/ldc.d
  source/dub/dub.d
  source/dub/generators/generator.d
  test/issue1867-lowmem.sh
  test/issue1867-lowmem/.gitignore
  test/issue1867-lowmem/.no_build
  test/issue1867-lowmem/.no_run
  test/issue1867-lowmem/.no_test
  test/issue1867-lowmem/dub.sdl
  test/issue1867-lowmem/dub.settings.json
  test/issue1867-lowmem/source/app.d
Labels: auto-merge

#2103 Fix #2046 - Dependencies specified with a path ignore optional settings
  source/dub/project.d
  test/issue2046-ignored-optional-with-path/.no_build
  test/issue2046-ignored-optional-with-path/.no_run
  test/issue2046-ignored-optional-with-path/.no_test
  test/issue2046-ignored-optional-with-path/dub.json
  test/issue2046-ignored-optional-with-path/dub.selections.json-nofoo
  test/issue2046-ignored-optional-with-path/dub.selections.json-usefoo
  test/issue2046-ignored-optional-with-path/libbar/dub.json
  test/issue2046-ignored-optional-with-path/libbar/source/libbar/bar.d
  test/issue2046-ignored-optional-with-path/libfoo/dub.json
  test/issue2046-ignored-optional-with-path/libfoo/source/libfoo/foo.d
  test/issue2046-ignored-optional-with-path/source/app.d
Labels: Bug Fix, auto-merge

#2109 Replacing rununittest.sh
  .github/workflows/main.yml
  .gitignore
  test/.gitignore
  test/0-init-fail-json.script.d
  test/0-init-fail-json.sh
  test/common/.no_build
  test/common/.no_run
  test/common/.no_test
  test/common/dub.sdl
  test/common/source/common.d
  test/run-unittest.d
Labels: auto-merge

#2115 merge stable
  source/dub/version_.d
Labels: auto-merge

#2116 Fixed a regression with DFLAGS environment variable and cached generated unittest
  source/dub/dub.d
  test/cache-generated-test-config.sh
Labels: Bug Fix

#2117 merge stable
  changelog/dmd-linker-dflags.dd
  changelog/visuald-copyfiles.dd
  source/dub/dub.d
  source/dub/version_.d
  test/cache-generated-test-config.sh
Labels: auto-merge
