Repository dlang/dub, pull requests merged in 2021-02, with the labels that each got.

#2087 Fix #2086 copyFiles in subPackage does not honour targetPath.
  source/dub/generators/generator.d
  test/issue2086-copyfiles-subpackage-targetpath.sh
  test/issue2086-copyfiles-subpackage-targetpath/.no_run
  test/issue2086-copyfiles-subpackage-targetpath/dub.json
  test/issue2086-copyfiles-subpackage-targetpath/sub/dub.json
  test/issue2086-copyfiles-subpackage-targetpath/sub/files/to_be_deployed.txt
  test/issue2086-copyfiles-subpackage-targetpath/sub/source/app.d
Labels: Bug Fix

#2106 merge stable
  source/dub/recipe/sdl.d
  source/dub/version_.d
Labels: Bug Fix

#2105 Actually copy copyFiles when building in Visual Studio.
  changelog/visuald-copyfiles.dd
  source/dub/generators/visuald.d
  test/issue1053-extra-files-visuald.sh
Labels: auto-merge-squash

#2108 import 'std.variant.Algebraic' properly
  source/dub/internal/sdlang/lexer.d
  source/dub/internal/sdlang/parser.d
Labels: auto-merge

#2107 merge stable
  source/dub/version_.d
Labels: Bug Fix, auto-merge

#2112 Fix single file package dynamic library
  source/dub/generators/generator.d
  test/issue1505-single-file-package-dynamic-library.d
  test/issue1505-single-file-package-dynamic-library.sh
Labels: auto-merge, enhancement
