Repository dlang/dub, pull requests merged in 2022-11, with the labels that each got.

#2526 Fix add-path based development workflow
  build.d
  source/dub/packagemanager.d
  test/prefer-add-path-packages.sh
Labels: regression

#2529 merge stable
  changelog/build_unittest.dd
  changelog/colored_output.dd
  changelog/configy_stricter_parsing.dd
  changelog/cov_ctfe.dd
  changelog/dpath.dd
  changelog/exitcodes.dd
  changelog/install_uninstall.dd
  changelog/make-copies-writable.dd
  changelog/overrides_deprecated.dd
  changelog/subpackage_short_syntax.dd
  changelog/subpackage_upgrade.dd
  source/dub/version_.d
Labels: auto-merge

#2536 Improve dub init custom template docs
  source/dub/commandline.d
Labels: trivial

#2537 Fixed dub init docs
  source/dub/commandline.d
Labels: trivial
