Repository dlang/dub, pull requests merged in 2022-07, with the labels that each got.

#2285 Add a command line option for upgrading all sub packages.
  changelog/subpackage_upgrade.dd
  source/dub/commandline.d
  source/dub/dub.d
  test/test-upgrade-subpackages.sh
  test/timeout.sh
Labels: auto-merge

#2295 merge stable
  source/dub/version_.d
Labels: auto-merge

#2298 Avoid needless string concat in log calls
  source/dub/commandline.d
  source/dub/internal/utils.d
  source/dub/packagemanager.d
  source/dub/packagesuppliers/filesystem.d
Labels: auto-merge

#2301 Deprecate once-called redundant getLatestPackage
  source/dub/commandline.d
  source/dub/dub.d
  source/dub/packagemanager.d
  source/dub/packagesuppliers/maven.d
Labels: auto-merge

#2304 getDefaultConfiguration(): Accept a const BuildPlatform argument
  source/dub/dub.d
  source/dub/generators/build.d
  source/dub/project.d
Labels: auto-merge

#2306 Dependency: Move `spec` / git ref inside of `Repository`
  source/dub/dependency.d
  source/dub/dub.d
  source/dub/project.d
  source/dub/recipe/sdl.d
Labels: auto-merge

#2307 PackageManager: Use PackageRecipe, not JSON, for dummy object
  source/dub/packagemanager.d
Labels: trivial, auto-merge

#2308 Dependency: Improve attribute annotation and prepare for SumType
  source/dub/dependency.d
  source/dub/internal/vibecompat/inet/path.d
  source/dub/recipe/packagerecipe.d
Labels: auto-merge

#2315 Deprecate duplicated JSON serialization for Dependency
  source/dub/dependency.d
  source/dub/project.d
Labels: auto-merge

#2317 Dependency: Remove top-level safe, apply to decl
  source/dub/dependency.d
Labels: auto-merge

#2320 Trivial: Remove a leftover debug statement
  source/dub/dub.d
Labels: auto-merge

#2318 sdl: Simplify Dependency parsing
  source/dub/recipe/sdl.d
Labels: auto-merge

#2321 Fix missing deserialization of fileVersion from dub.selections.json
  source/dub/project.d
Labels: auto-merge

#2323 commandline: Catch Exception, not Throwable
  source/dub/commandline.d
Labels: auto-merge

#2325 Upgrade dub.selections.json with vibe-d v0.9.5
  dub.selections.json
Labels: auto-merge

#2330 Fail fast on Windows.
  .github/workflows/main.yml
Labels: auto-merge-squash, CI

#2332 Trivial: Streamline code when package not found in project
  source/dub/project.d
Labels: auto-merge-squash, Refactoring

#2335 Trivial: Deduplicate GeneratorSettings initialization
  source/dub/dub.d
Labels: auto-merge

#2342 Trivial: Deprecate Dub.remove(Package, bool)
  source/dub/dub.d
Labels: auto-merge

#2340 Remove long-deprecated 'install' and 'uninstall' command
  changelog/install_uninstall.dd
  source/dub/commandline.d
Labels: auto-merge

#2344 use json.get directly instead of casting
  source/dub/project.d
Labels: auto-merge

#2346 Commandline: Do not duplicate GeneratorSettings fields
  source/dub/commandline.d
Labels: auto-merge

#2309 CI: Fix script for issue1505
  test/issue1505-single-file-package-dynamic-library.sh
Labels: auto-merge

#2343 Use Configy to read user settings (`settings.json`) too
  source/dub/dub.d
Labels: auto-merge
