Repository dlang/dub, pull requests merged in 2022-08, with the labels that each got.

#2353 Some `PackageManager` cleanup
  source/dub/commandline.d
  source/dub/dub.d
  source/dub/packagemanager.d
Labels: auto-merge

#2357 Deprecate Dependency.matchesAny in favor of VersionRange
  source/dub/dependency.d
Labels: auto-merge

#2356 Dependency: Ensures call to version_ are on version-containing object
  source/dub/dependency.d
Labels: auto-merge

#2361 Default `dub init` to SDL
  source/dub/commandline.d
Labels: auto-merge

#2362 Revert "Default `dub init` to SDL"
  source/dub/commandline.d
Labels: auto-merge

#2367 Integrate Configy colored output with dub's
  source/configy/Read.d
  source/dub/dub.d
  source/dub/internal/logging.d
  source/dub/project.d
Labels: auto-merge

#2368 Configy: Implement soundexer-based key-matching in strict mode
  source/configy/Exceptions.d
  source/configy/Test.d
Labels: auto-merge

#2372 Improve searchPackages naming+docs
  source/dub/dub.d
Labels: auto-merge

#2373 PackageManager: Move some `Location`-specific routines to `Location`
  source/dub/packagemanager.d
Labels: auto-merge

#2378 Configy: Synchronize with upstream changes
  source/configy/Attributes.d
  source/configy/Exceptions.d
  source/configy/Read.d
  source/configy/Test.d
Labels: auto-merge

#2384 Fix #2383
  source/dub/init.d
Labels: auto-merge

#2389 Fix x86 OMF build support
  source/dub/compilers/dmd.d
Labels: auto-merge-squash

#2404 Correct git ignores
  .gitignore
  test/.gitignore
Labels: auto-merge

#2405 Trivial: Add attributes and documentation to PackageRecipe
  source/dub/recipe/packagerecipe.d
Labels: auto-merge

#2416 Dependency: Take advantage of -preview=in
  source/dub/dependency.d
Labels: auto-merge

#2382 Forward flag -color to compiler calls
  source/dub/commandline.d
  source/dub/compilers/buildsettings.d
  source/dub/compilers/dmd.d
  source/dub/compilers/gdc.d
  source/dub/compilers/ldc.d
  source/dub/generators/build.d
  test/colored-output.sh
Labels: auto-merge

#2417 Trivial: Group 'Dub' class ctor/init together
  source/dub/dub.d
Labels: auto-merge

#2421 Avoid calls to .dup in cmake.d
  source/dub/generators/cmake.d
Labels: auto-merge

#2418 Dub: Remove unused m_overrideSearchPaths member
  source/dub/dub.d
Labels: auto-merge

#2423 PackageManager: Deprecate overloads of getPackage with string version
  source/dub/dub.d
  source/dub/packagemanager.d
Labels: auto-merge

#2424 only do main file searching when neccessary
  source/dub/package_.d
Labels: auto-merge

#2426 Remove redundant null checks in DependencyVersionResolver
  source/dub/dub.d
Labels: auto-merge

#2395 Windows: Don't copy import .lib & .exp files for executables
  source/dub/generators/build.d
Labels: needs review

#2430 Integrate `dependencyBuildSettings` into dependencies
  source/dub/generators/generator.d
  source/dub/package_.d
  source/dub/recipe/json.d
  source/dub/recipe/packagerecipe.d
  source/dub/recipe/sdl.d
Labels: auto-merge

#2436 remove unneccessary warning prefix
  source/dub/dub.d
Labels: trivial

#2435 Remove redundant lookup when searching for a tool
  source/dub/dub.d
Labels: auto-merge

#2440 Remove 'unknown' version
  source/dub/dependency.d
  source/dub/package_.d
Labels: auto-merge

#2437 Trivial: Convert some spaces to tabs
  source/dub/internal/utils.d
  source/dub/packagemanager.d
Labels: trivial
