Repository dlang/dub, pull requests merged in 2022-10, with the labels that each got.

#2319 GH CI: Update runner OS and actions/checkout version
  .github/workflows/main.yml
Labels: blocked

#2495 merge stable
  source/dub/version_.d
Labels: auto-merge, stable -> master

#2497 Deprecate yet another dub.remove overload using force_remove
  source/dub/dub.d
Labels: auto-merge

#2498 Deprecate `PackageManager.refresh(true)`, only expose `refresh()`
  source/dub/packagemanager.d
  source/dub/project.d
Labels: auto-merge

#2510 Make the test runner code more readable
  source/dub/project.d
Labels: trivial

#2520 Move existsDirectory next to existsFile
  source/dub/internal/utils.d
  source/dub/internal/vibecompat/core/file.d
Labels: trivial
