Repository dlang/dub, pull requests merged in 2023-03, with the labels that each got.

#2609 update version to v1.32.0-beta.1
  source/dub/version_.d
Labels: auto-merge, stable -> master

#2614 Make all static library exports contribute to dlls on Windows
  changelog/static_libraries_exported_dll.dd
  source/dub/compilers/compiler.d
  source/dub/compilers/dmd.d
  source/dub/compilers/gdc.d
  source/dub/compilers/ldc.d
  source/dub/generators/build.d
Labels: auto-merge

#2625 update version to v1.32.0-rc.1
  source/dub/version_.d
Labels: stable -> master
