Repository dlang/dub, pull requests merged in 2024-06, with the labels that each got.

#2913 merge stable
  source/dub/internal/utils.d
  source/dub/version_.d
Labels: stable -> master

#2916 Remove support for OMF, make MsCOFF be x86
  source/dub/compilers/dmd.d
  test/win32_default.d
  test/win32_default.script.d
Labels: auto-merge

#2921 Remove redundant add-path shell script test
  test/prefer-add-path-packages.sh
Labels: auto-merge

#2920 Clear up two deprecations triggering in unittest
  source/dub/generators/build.d
  source/dub/generators/generator.d
Labels: auto-merge

#2922 Move the I/O part of Project.loadSelections to PackageManager
  source/dub/dub.d
  source/dub/internal/configy/Read.d
  source/dub/packagemanager.d
  source/dub/project.d
  source/dub/test/base.d
Labels: auto-merge

#2919 Clear an unprinted deprecation during dub build
  source/dub/commandline.d
  source/dub/dub.d
Labels: auto-merge

#2930 Trivial: Remove internal deprecations
  source/dub/commandline.d
  source/dub/internal/utils.d
Labels: auto-merge

#2932 merge stable
  source/dub/version_.d
Labels: auto-merge, stable -> master

#2942 [stable] Drop support for LDC v1.26.0
  .github/workflows/main.yml
  source/app.d
Labels: auto-merge

#2944 Refactor filesystem abstraction to and use it in production
  build-files.txt
  source/dub/dub.d
  source/dub/internal/io/filesystem.d
  source/dub/internal/io/mockfs.d
  source/dub/internal/io/realfs.d
  source/dub/packagemanager.d
  source/dub/test/base.d
  source/dub/test/dependencies.d
  source/dub/test/other.d
  source/dub/test/selections_from_parent_dir.d
  source/dub/test/subpackages.d
Labels: auto-merge
